apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: goaltrajectory-ai
  labels:
    app: goaltrajectory-ai
    component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: goaltrajectory-ai
    component: backend
  sessionAffinity: None

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: goaltrajectory-ai
  labels:
    app: goaltrajectory-ai
    component: backend
automountServiceAccountToken: false