version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      target: development
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 60s

  backend:
    build:
      context: ./backend
      target: development
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/goaltrajectory
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - FASTAPI_ENV=development
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      - ./backend:/app
      - /app/venv
      - /app/__pycache__
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    ports:
      - "8000:8000"
      - "5678:5678"  # Debug port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 60s

  chromadb:
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_LOG_LEVEL=DEBUG
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 45s

  postgres:
    environment:
      - POSTGRES_DB=goaltrajectory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--auth-host=trust
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d goaltrajectory"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 45s

  # Development tools and utilities
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@goaltrajectory.ai
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network