apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: chromadb
  namespace: goaltrajectory-ai

resources:
- configmap.yaml
- pvc.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- network-policy.yaml
- servicemonitor.yaml

commonLabels:
  app: chromadb
  component: database
  version: v1.0.0

images:
- name: chromadb/chroma
  newTag: latest

replicas:
- name: chromadb
  count: 1

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: chromadb
  spec:
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8000"
          prometheus.io/path: "/api/v1/heartbeat"