apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chromadb-network-policy
  namespace: goaltrajectory-ai
  labels:
    app: chromadb
    component: database
spec:
  podSelector:
    matchLabels:
      app: chromadb
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from backend pods
  - from:
    - podSelector:
        matchLabels:
          app: backend
    ports:
    - protocol: TCP
      port: 8000
  # Allow traffic from monitoring (if using Prometheus)
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8000
  # Allow health checks from kube-system
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 8000
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow outbound HTTPS for updates (if needed)
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow communication within the same namespace
  - to:
    - namespaceSelector:
        matchLabels:
          name: goaltrajectory-ai