apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chromadb-metrics
  namespace: goaltrajectory-ai
  labels:
    app: chromadb
    component: database
spec:
  selector:
    matchLabels:
      app: chromadb
  endpoints:
  - port: http
    path: /api/v1/heartbeat
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - goaltrajectory-ai
---
# Alternative: PodMonitor for direct pod monitoring
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: chromadb-pod-metrics
  namespace: goaltrajectory-ai
  labels:
    app: chromadb
    component: database
spec:
  selector:
    matchLabels:
      app: chromadb
  podMetricsEndpoints:
  - port: http
    path: /api/v1/heartbeat
    interval: 30s
    scrapeTimeout: 10s