apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-network-policy
  namespace: goaltrajectory
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress traffic from anywhere on HTTP/HTTPS ports
  - from: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8443
  egress:
  # Allow egress to frontend service
  - to:
    - namespaceSelector:
        matchLabels:
          name: goaltrajectory
      podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 3000
  
  # Allow egress to backend service
  - to:
    - namespaceSelector:
        matchLabels:
          name: goaltrajectory
      podSelector:
        matchLabels:
          app: backend
    ports:
    - protocol: TCP
      port: 8000
  
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  
  # Allow HTTPS for cert-manager ACME challenges
  - to: []
    ports:
    - protocol: TCP
      port: 443

---
# Network policy for frontend pods to receive ingress traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-ingress-policy
  namespace: goaltrajectory
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  # Allow traffic from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 3000
  
  # Allow traffic from same namespace (for service mesh)
  - from:
    - namespaceSelector:
        matchLabels:
          name: goaltrajectory
    ports:
    - protocol: TCP
      port: 3000

---
# Network policy for backend pods to receive ingress traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-ingress-policy
  namespace: goaltrajectory
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  ingress:
  # Allow traffic from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
  
  # Allow traffic from same namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: goaltrajectory
    ports:
    - protocol: TCP
      port: 8000
  
  # Allow traffic from frontend pods
  - from:
    - namespaceSelector:
        matchLabels:
          name: goaltrajectory
      podSelector:
        matchLabels:
          app: frontend
    ports:
    - protocol: TCP
      port: 8000