apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: goaltrajectory-ai
  labels:
    app: goaltrajectory-ai
    component: frontend
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: goaltrajectory-ai
      component: frontend
  template:
    metadata:
      labels:
        app: goaltrajectory-ai
        component: frontend
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      serviceAccountName: frontend-service-account
      priorityClassName: goaltrajectory-ai-priority
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: frontend
        image: goaltrajectory-ai/frontend:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        # Environment variables from ConfigMap
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NODE_ENV
        - name: BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_HOST
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_PORT
        # Build the backend URL from host and port
        - name: NEXT_PUBLIC_API_URL
          value: "http://$(BACKEND_HOST):$(BACKEND_PORT)"
        # Sensitive environment variables from Secrets
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXTAUTH_SECRET
        - name: NEXTAUTH_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: NEXTAUTH_URL
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SUPABASE_ANON_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        - name: nextjs-cache
          mountPath: /app/.next/cache
        - name: nextjs-static
          mountPath: /app/.next/static
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: nextjs-cache
        emptyDir: {}
      - name: nextjs-static
        emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30