apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: goaltrajectory-ai
  labels:
    app: goaltrajectory-ai
    component: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
  selector:
    app: goaltrajectory-ai
    component: frontend
  sessionAffinity: None

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-account
  namespace: goaltrajectory-ai
  labels:
    app: goaltrajectory-ai
    component: frontend
automountServiceAccountToken: false